import type { MenuItem } from "./types";

export const menuItems: MenuItem[] = [
  {
    id: "chap-1",
    name: "Chapata de Pollo",
    description: "Juicy grilled chicken, lettuce, tomato, and our special sauce.",
    price: 85.0,
    category: "Chapatas",
    imageId: "chapata-pollo",
  },
  {
    id: "chap-2",
    name: "Chapata de Jamón y Queso",
    description: "Classic ham and cheese, melted to perfection.",
    price: 75.0,
    category: "Chapatas",
    imageId: "chapata-jamon",
  },
  {
    id: "chap-3",
    name: "Chapata Vegetariana",
    description: "A mix of fresh grilled vegetables, avocado, and panela cheese.",
    price: 80.0,
    category: "Chapatas",
    imageId: "chapata-vegetariana",
  },
  {
    id: "chap-4",
    name: "Chapata de Carnes Frías",
    description: "Salami, pepperoni, and ham with provolone cheese.",
    price: 95.0,
    category: "Chapatas",
    imageId: "chapata-carnes-frias",
  },
  {
    id: "bev-1",
    name: "Agua Fresca del Día",
    description: "Ask for today's flavor. Horchata, Jamaica, or Tamarindo.",
    price: 30.0,
    category: "Bebidas",
    imageId: "bebida-agua-fresca",
  },
  {
    id: "bev-2",
    name: "Refresco",
    description: "Coca-Cola, Sprite, Fanta, Mundet.",
    price: 25.0,
    category: "Bebidas",
    imageId: "bebida-refresco",
  },
  {
    id: "bev-3",
    name: "Café Americano",
    description: "Freshly brewed hot coffee.",
    price: 35.0,
    category: "Bebidas",
    imageId: "bebida-cafe",
  },
  {
    id: "juice-1",
    name: "Jugo de Naranja",
    description: "100% natural, freshly squeezed orange juice.",
    price: 40.0,
    category: "Jugos",
    imageId: "jugo-naranja",
  },
  {
    id: "juice-2",
    name: "Jugo Verde",
    description: "Celery, pineapple, parsley, nopal, and orange juice.",
    price: 45.0,
    category: "Jugos",
    imageId: "jugo-verde",
  },
  {
    id: "juice-3",
    name: "Jugo de Zanahoria",
    description: "Freshly pressed carrot juice.",
    price: 40.0,
    category: "Jugos",
    imageId: "jugo-zanahoria",
  },
];
